spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5439/avisUtilisateurs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 9025
jwt:
  secret: rQPV3snc439paYfTGfPO3matOk3IoS/kXbFk+Z/dEloNGEc03wx93JYmExMLDjc8
